name: frog_task_list
description: "Task list using mvvm(viewmodels using riverpod) and clean architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.0.1
  http: ^1.2.1
  sembast: ^3.7.1
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  path_provider: ^2.1.4
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_ce_generator: ^1.8.2
  freezed: ^3.0.4
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true