// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:frog_task_list/module/auth/data/model/user.dart';
import 'package:frog_task_list/module/todo/data/model/todo.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(TodoAdapter());
    registerAdapter(UserAdapter());
  }
}
